version: "3.9"

services:
  backend:
    build: .
    container_name: nest_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - enquete_net
    command: ["sh", "./wait-for.sh", "db", "3306", "npm", "run", "start:prod"]

  db:
    image: mysql:8
    container_name: enquete_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - enquete_net

volumes:
  db_data:

networks:
  enquete_net:
    driver: bridge
